# Generated by Django 2.2 on 2018-08-13 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderlineitems',
            old_name='goodsid',
            new_name='goods',
        ),
        migrations.RenameField(
            model_name='orderlineitems',
            old_name='orderid',
            new_name='orders',
        ),
    ]
