# Generated by Django 2.2 on 2018-08-13 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20180813_1259'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderLineItems',
            new_name='OrderLineItem',
        ),
    ]
