# Generated by Django 2.2 on 2018-08-13 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20180813_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderlineitem',
            name='sub_total',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='orders',
            name='total',
            field=models.FloatField(default=0.0),
        ),
    ]
